### ISSUE TITLE
Inviten a Richi

### ISSUE THREAD

**Issue by Geeermy** [norman123123/proyectoSO#16]
¡Hola!

Si no lo han hecho, inviten a Richi al repositorio para llevar a cabo la recolección.

¡Éxito!

**Comment by naoliden** [comment]
Se supone que ya esta invitado como colaborador

<img width="746" alt="Screenshot 2019-05-23 at 12 42 21" src="https://user-images.githubusercontent.com/8712696/58270609-36b5f800-7d58-11e9-9bb5-4158f4053e3a.png">

**Comment by Geeermy** [comment]
Genial. Estoy verificando para no tener problemas después. :)
